-- Expand FinishingPackage enum
ALTER TYPE "FinishingPackage" ADD VALUE IF NOT EXISTS 'FURNITURE';
ALTER TYPE "FinishingPackage" ADD VALUE IF NOT EXISTS 'FURNITURE_AND_AC';
ALTER TYPE "FinishingPackage" ADD VALUE IF NOT EXISTS 'FINISHING';
ALTER TYPE "FinishingPackage" ADD VALUE IF NOT EXISTS 'COMPANY_FINISHING';

-- Expand HandoverStatus enum with standardized action/warning types
-- NOTE: Data migration to new values is in the following migration (PG requires enum
-- values to be committed before they can be used in UPDATE statements).
ALTER TYPE "HandoverStatus" ADD VALUE IF NOT EXISTS 'DELIVERY_PROTOCOL';
ALTER TYPE "HandoverStatus" ADD VALUE IF NOT EXISTS 'DELIVERY_EXTENSION';
ALTER TYPE "HandoverStatus" ADD VALUE IF NOT EXISTS 'FINISHING_CHANGE';
ALTER TYPE "HandoverStatus" ADD VALUE IF NOT EXISTS 'UNIT_SWAP';
ALTER TYPE "HandoverStatus" ADD VALUE IF NOT EXISTS 'NEW_CONTRACT';
ALTER TYPE "HandoverStatus" ADD VALUE IF NOT EXISTS 'WAIVER';
ALTER TYPE "HandoverStatus" ADD VALUE IF NOT EXISTS 'REFUSED_DELIVERY';
ALTER TYPE "HandoverStatus" ADD VALUE IF NOT EXISTS 'REFUSED_EXTENSION';
ALTER TYPE "HandoverStatus" ADD VALUE IF NOT EXISTS 'INSTALLMENT_STOP_WARNING';
ALTER TYPE "HandoverStatus" ADD VALUE IF NOT EXISTS 'DELIVERY_WARNING';
